# Generated by Django 6.0 on 2025-12-18 19:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_remove_review_guest_name_remove_review_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='guest_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
