# Generated by Django 6.0 on 2025-12-22 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0014_alter_answer_user_alter_question_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='bio',
            field=models.TextField(blank=True, help_text='توضیحاتی درباره سوابق و تخصص استاد', verbose_name='بیوگرافی'),
        ),
        migrations.AddField(
            model_name='professor',
            name='image',
            field=models.ImageField(blank=True, help_text='عکس استاد با ابعاد 300x300 پیکسل', null=True, upload_to='professors/', verbose_name='عکس پروفایل'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='department',
            field=models.CharField(blank=True, max_length=200, verbose_name='دپارتمان'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام'),
        ),
    ]
