# Generated by Django 6.0 on 2025-12-23 13:47

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0016_alter_answer_options_alter_answervote_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDailyLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='تاریخ')),
                ('review_count', models.IntegerField(default=0, verbose_name='تعداد نظرات')),
                ('question_count', models.IntegerField(default=0, verbose_name='تعداد پرسش\u200cها')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'محدودیت روزانه',
                'verbose_name_plural': 'محدودیت\u200cهای روزانه',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
