# Generated by Django 6.0 on 2025-12-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_review_guest_name_question_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_visible',
        ),
        migrations.AlterField(
            model_name='answer',
            name='guest_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='guest_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='guest_name',
            field=models.CharField(max_length=100),
        ),
    ]
