# Generated by Django 6.0 on 2025-12-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_remove_question_is_visible_alter_answer_guest_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='guest_name',
        ),
        migrations.RemoveField(
            model_name='review',
            name='status',
        ),
        migrations.AddField(
            model_name='question',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
