# Generated by Django 6.0 on 2025-12-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_review_guest_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
